project:
  type: website

website:
  title: "MMES565FINAL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Methods.qmd
      - Statistics.qmd
      - Other Projects.qmd
      - about.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    
resources: 
  -PHOTOS/**

editor: visual

