project:
  type: website
  
output-dir: _site

website:
  title: "MMES565FINAL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Methods.qmd
        text: Methods
      - href: Statistics.qmd
        text: Statistics
      - href: other-projects.qmd
        text: Other Projects
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
